[package]
name = "pocket-ytm"
version = "0.1.4"
edition = "2024"
description = "A zero-DOM native YouTube Music client built with GPUI"
license = "MIT"

[dependencies]
anyhow = "1.0"
base64 = "0.22"
ed25519-dalek = "2.2"
env_logger = "0.11"
futures = "0.3"
gpui = { version = "0.2.2", features = ["macos-blade"] }
gpui-component = { version = "0.5.1", default-features = false }
gpui_http_client = "0.2.2"
image = "0.25.10"
log = "0.4"
parking_lot = "0.12"
reqwest = { version = "0.13", default-features = false, features = ["blocking", "native-tls", "charset", "http2", "json", "system-proxy"] }
rodio = { version = "0.22.2", default-features = false, features = ["playback", "wav"] }
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
stream-download = { version = "0.24.3", default-features = false, features = ["process", "temp-storage"] }
tempfile = "3.23.0"
tokio = { version = "1.47", features = ["rt-multi-thread", "time", "process", "io-util"] }
zip = { version = "4.6", default-features = false, features = ["deflate"] }

[profile.release]
lto = "thin"
strip = true
